# Generated by Django 3.2.18 on 2023-02-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips_input', '0001_initial'),
        ('tips_dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='PlayerPoints',
        ),
    ]
