# Generated by Django 3.2.18 on 2023-03-02 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bets_input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('fastest_lap', models.BooleanField(default=False)),
                ('dotd', models.BooleanField(default=False)),
                ('dnf', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets_input.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets_input.race')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets_input.player')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets_input.race')),
            ],
        ),
    ]
