# Generated by Django 3.2.18 on 2023-03-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bets_input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('position_quali', models.PositiveSmallIntegerField()),
                ('position_sprint', models.PositiveSmallIntegerField()),
                ('fastest_lap', models.BooleanField(default=False)),
                ('dotd', models.BooleanField(default=False)),
                ('dnf', models.BooleanField(default=False)),
                ('dnf_sprint', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets_input.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets_input.race')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPointsTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_total', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets_input.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_race', models.IntegerField()),
                ('points_sprint', models.IntegerField()),
                ('points_quali', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets_input.player')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets_input.race')),
            ],
        ),
        migrations.CreateModel(
            name='EventAssessmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_type', models.CharField(choices=[('race', 'race'), ('sprint', 'sprint'), ('quali', 'quali')], max_length=10)),
                ('was_assessed', models.BooleanField(default=False)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets_input.race')),
            ],
        ),
    ]
