# Generated by Django 3.2.18 on 2023-03-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets_dash', '0002_auto_20230305_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpoints',
            name='points',
        ),
        migrations.AddField(
            model_name='playerpoints',
            name='points_quali',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerpoints',
            name='points_race',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerpoints',
            name='points_sprint',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
