# Generated by Django 3.2.18 on 2023-03-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets_dash', '0004_playerpointstotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerpointstotal',
            name='points_total',
            field=models.IntegerField(default=0),
        ),
    ]
