bets = [
    {
        "race_id": 1,
        "player_id": 1,  # denis
        "quali_order": [
            "ALO",
            "VER",
            "HAM",
            "LEC",
            "PER",
            "RUS",
            "STR",
            "NOR",
            "SAI",
            "GAS",
            "HUL",
            "OCO",
            "BOT",
            "ZHO",
            "ALB",
            "MAG",
            "SAR",
            "DEV",
            "PIA",
            "TSU",
        ],
        "sprint_order": [],
        "race_order": [
            "VER",
            "LEC",
            "PER",
            "RUS",
            "ALO",
            "SAI",
            "HAM",
            "STR",
            "OCO",
            "HUL",
            "NOR",
            "BOT",
            "ZHO",
            "MAG",
            "TSU",
            "ALB",
            "GAS",
            "SAR",
            "DEV",
            "PIA",
        ],
        "dnfs": ["GAS", "TSU", "SAR"],
        "fastest_lap": "LEC",
        "dotd": "ALO",
    },
    {
        "race_id": 1,
        "player_id": 2,  # tristan
        "quali_order": [
            "VER",
            "PER",
            "ALO",
            "LEC",
            "SAI",
            "HAM",
            "RUS",
            "STR",
            "GAS",
            "OCO",
            "ZHO",
            "HUL",
            "NOR",
            "PIA",
            "BOT",
            "MAG",
            "ALB",
            "TSU",
            "DEV",
            "SAR",
        ],
        "sprint_order": [],
        "race_order": [
            "VER",
            "PER",
            "LEC",
            "ALO",
            "SAI",
            "RUS",
            "HAM",
            "STR",
            "HUL",
            "OCO",
            "ALB",
            "ZHO",
            "MAG",
            "BOT",
            "GAS",
            "NOR",
            "PIA",
            "TSU",
            "SAR",
            "DEV",
        ],
        "dnfs": ["DEV", "GAS", "MAG"],
        "fastest_lap": "VER",
        "dotd": "ALO",
    },
    {
        "race_id": 1,
        "player_id": 3,  # tomas
        "quali_order": [],
        "sprint_order": [],
        "race_order": [
            "VER",
            "PER",
            "LEC",
            "SAI",
            "RUS",
            "ALO",
            "HAM",
            "STR",
            "OCO",
            "HUL",
            "BOT",
            "NOR",
            "ZHO",
            "ALB",
            "MAG",
            "TSU",
            "GAS",
            "DEV",
            "SAR",
            "PIA",
        ],
        "dnfs": [],
        "fastest_lap": "",
        "dotd": "",
    },
    {
        "race_id": 1,
        "player_id": 4,  # edo
        "quali_order": [
            "VER",
            "LEC",
            "ALO",
            "PER",
            "SAI",
            "HAM",
            "RUS",
            "MAG",
            "STR",
            "BOT",
            "OCO",
            "NOR",
            "GAS",
            "HUL",
            "ZHO",
            "PIA",
            "TSU",
            "DEV",
            "ALB",
            "SAR",
        ],
        "sprint_order": [],
        "race_order": [
            "VER",
            "PER",
            "LEC",
            "SAI",
            "RUS",
            "ALO",
            "HAM",
            "STR",
            "HUL",
            "OCO",
            "NOR",
            "BOT",
            "MAG",
            "ZHO",
            "GAS",
            "ALB",
            "TSU",
            "PIA",
            "SAR",
            "DEV",
        ],
        "dnfs": ["DEV", "STR", "ZHO"],
        "fastest_lap": "VER",
        "dotd": "ALO",
    },
    {
        "race_id": 1,
        "player_id": 5,  # lilly
        "quali_order": [
            "VER",
            "ALO",
            "HAM",
            "PER",
            "LEC",
            "RUS",
            "STR",
            "SAI",
            "GAS",
            "OCO",
            "NOR",
            "MAG",
            "PIA",
            "HUL",
            "ZHO",
            "BOT",
            "TSU",
            "ALB",
            "DEV",
            "SAR",
        ],
        "sprint_order": [],
        "race_order": [
            "VER",
            "LEC",
            "PER",
            "SAI",
            "HAM",
            "RUS",
            "ALO",
            "OCO",
            "STR",
            "HUL",
            "BOT",
            "NOR",
            "ZHO",
            "MAG",
            "GAS",
            "TSU",
            "ALB",
            "SAR",
            "PIA",
            "DEV",
        ],
        "dnfs": ["RUS", "STR", "TSU"],
        "fastest_lap": "VER",
        "dotd": "ALO",
    },
    {
        "race_id": 1,
        "player_id": 6,  # Nina
        "quali_order": [
            "VER",
            "LEC",
            "PER",
            "HAM",
            "ALO",
            "SAI",
            "HUL",
            "GAS",
            "RUS",
            "BOT",
            "MAG",
            "STR",
            "NOR",
            "OCO",
            "ALB",
            "ZHO",
            "PIA",
            "DEV",
            "TSU",
            "SAR",
        ],
        "sprint_order": [],
        "race_order": [
            "VER",
            "PER",
            "LEC",
            "SAI",
            "HAM",
            "ALO",
            "RUS",
            "BOT",
            "OCO",
            "NOR",
            "HUL",
            "ZHO",
            "ALB",
            "STR",
            "GAS",
            "DEV",
            "TSU",
            "MAG",
            "SAR",
            "PIA",
        ],
        "dnfs": ["SAR", "TSU", "PIA"],
        "fastest_lap": "VER",
        "dotd": "ALO",
    },
    {
        "race_id": 1,
        "player_id": 7,  # Jozef
        "quali_order": [],
        "sprint_order": [],
        "race_order": [
            "VER",
            "LEC",
            "PER",
            "HAM",
            "ALO",
            "RUS",
            "SAI",
            "STR",
            "OCO",
            "HUL",
            "BOT",
            "ZHO",
            "NOR",
            "ALB",
            "GAS",
            "MAG",
            "TSU",
            "PIA",
            "SAR",
            "DEV",
        ],
        "dnfs": ["DEV", "SAR", "PIA"],
        "fastest_lap": "VER",
        "dotd": "ALO",
    },
]
