# Generated by Django 3.2.18 on 2023-03-06 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets_input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racebet',
            name='is_default_quali',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='racebet',
            name='is_default_race',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='racebet',
            name='is_default_sprint',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PlayerPlacedBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_type', models.CharField(choices=[('race', 'race'), ('sprint', 'sprint'), ('quali', 'quali')], max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets_input.player')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets_input.race')),
            ],
        ),
    ]
