# Generated by Django 3.2.18 on 2023-03-06 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets_input', '0002_auto_20230306_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racebet',
            name='is_default_quali',
        ),
        migrations.RemoveField(
            model_name='racebet',
            name='is_default_race',
        ),
        migrations.RemoveField(
            model_name='racebet',
            name='is_default_sprint',
        ),
    ]
