# Generated by Django 3.2.18 on 2023-03-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets_input', '0003_auto_20230306_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='datetime_of_quali_gmt',
            field=models.DateTimeField(default='2020-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='datetime_of_sprint_gmt',
            field=models.DateTimeField(default='2020-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
