RACE_SLIDER = "race-slider"
PLAYER_DROPDOWN = "player-dropdown"
RACETYPE_DROPDOWN = "race-type-dropdown"
DRAG_CONTAINER_DRIVERS = "drag-container-drivers"
CURRENT_ORDER_OF_DRIVERS = "current-order-of-drivers"
RESULTS_OVERVIEW = "results-overview"
