# Generated by Django 3.2.18 on 2023-03-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='abbreviation',
            field=models.CharField(default='ABB', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racetip',
            name='dnf_sprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='racetip',
            name='position_sprint',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
