# Generated by Django 3.2.18 on 2023-03-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_input', '0002_auto_20230301_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lc_name',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
    ]
